# Generated by Django 2.1.2 on 2018-10-22 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона должен соотвтетствовать следующему формату: 79998887766. Разрешенная длина от 9 до 15 символов', regex='^\\d{9,15}$')], verbose_name='Номер телефона')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина добавления')),
                ('status', models.BooleanField(choices=[(True, 'В черном списке'), (False, 'Не в черном списке')], editable=False, verbose_name='Статус')),
                ('excluded_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата удаления')),
                ('added_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='who_added', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлено')),
                ('excluded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='who_removed', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено')),
            ],
        ),
    ]
